import 'package:flutter/material.dart';
import 'package:islami/UI/app_theme/theme.dart';
import 'package:islami/UI/ui_utils.dart';
import 'package:islami/widgits/surah_title.dart';

class QuranTab extends StatelessWidget {
  final List<String> arabicQuranSuras = [
  "الفاتحه",
  "البقرة",
  "آل عمران",
  "النساء",
  "المائدة",
  "الأنعام",
  "الأعراف",
  "الأنفال",
  "التوبة",
  "يونس",
  "هود",
  "يوسف",
  "الرعد",
  "إبراهيم",
  "الحجر",
  "النحل",
  "الإسراء",
  "الكهف",
  "مريم",
  "طه",
  "الأنبياء",
  "الحج",
  "المؤمنون",
  "النّور",
  "الفرقان",
  "الشعراء",
  "النّمل",
  "القصص",
  "العنكبوت",
  "الرّوم",
  "لقمان",
  "السجدة",
  "الأحزاب",
  "سبأ",
  "فاطر",
  "يس",
  "الصافات",
  "ص",
  "الزمر",
  "غافر",
  "فصّلت",
  "الشورى",
  "الزخرف",
  "الدّخان",
  "الجاثية",
  "الأحقاف",
  "محمد",
  "الفتح",
  "الحجرات",
  "ق",
  "الذاريات",
  "الطور",
  "النجم",
  "القمر",
  "الرحمن",
  "الواقعة",
  "الحديد",
  "المجادلة",
  "الحشر",
  "الممتحنة",
  "الصف",
  "الجمعة",
  "المنافقون",
  "التغابن",
  "الطلاق",
  "التحريم",
  "الملك",
  "القلم",
  "الحاقة",
  "المعارج",
  "نوح",
  "الجن",
  "المزّمّل",
  "المدّثر",
  "القيامة",
  "الإنسان",
  "المرسلات",
  "النبأ",
  "النازعات",
  "عبس",
  "التكوير",
  "الإنفطار",
  "المطفّفين",
  "الإنشقاق",
  "البروج",
  "الطارق",
  "الأعلى",
  "الغاشية",
  "الفجر",
  "البلد",
  "الشمس",
  "الليل",
  "الضحى",
  "الشرح",
  "التين",
  "العلق",
  "القدر",
  "البينة",
  "الزلزلة",
  "العاديات",
  "القارعة",
  "التكاثر",
  "العصر",
  "الهمزة",
  "الفيل",
  "قريش",
  "الماعون",
  "الكوثر",
  "الكافرون",
  "النصر",
  "المسد",
  "الإخلاص",
  "الفلق",
  "الناس"
];

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Image.asset(getImagePath("qur2an_screen_logo.png")),
       Divider(),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
          Expanded(child: Text("Surah Name",
           textAlign: TextAlign.center,
           style: TextStyle( color: Colors.black, fontSize: 23, fontWeight: FontWeight.w500),),
          ),
            const SizedBox(
              height: 35,
              child: VerticalDivider(),
            ),
          Expanded(child: Text("Verses Number",
    textAlign: TextAlign.center,
    style: TextStyle( color: Colors.black, fontSize: 23, fontWeight: FontWeight.w500),)
    )],),
        Divider(),
        Expanded(
          child: ListView.builder(
            itemCount: arabicQuranSuras.length,
              itemBuilder: (context, index) {
                return SurahTitle(arabicQuranSuras[index],index);
              }, ),
        ),



      ],
    );
  }
}
